name = "DoubleExponentialFormulas"
uuid = "eb426421-6452-4132-80ef-4b100a757ac5"
authors = ["Masaaki Nakamura"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
